# Generated by Django 3.0.7 on 2021-04-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiOneToOnerelation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiOneToOnerelation.PostsRates'),
        ),
    ]
