# Generated by Django 3.0.7 on 2021-04-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210428_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('year_of_warranty', models.PositiveIntegerField(default=1)),
                ('finanace_plan', models.CharField(default='unavailable', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carspecs',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.CarPlan'),
        ),
    ]
