# Generated by Django 3.0.7 on 2021-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Albuma',
        ),
    ]
